### ISSUE TITLE
Error in documentation for installation

### ISSUE THREAD

**Issue by abinashmeher999** [muhrix/kinect_aux#2]
The installation instructions given at http://wiki.ros.org/kinect_aux#Ubuntu seems to have a typo.
`$ sudo apt-get install ros-indigo-kinect_aux`
should be changed to
`$ sudo apt-get install ros-indigo-kinect-aux`
that is the `_` between `kinect` and `aux` to be changed to `-`.

**Comment by muhrix** [comment]
Thank you very much for spotting that, @abinashmeher999 !
I've just fixed the typos.
